FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund

FROM node:22-alpine AS build
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1 BUILD_STANDALONE=1
ARG PROGRAMO_DEPLOYMENT_ENV=preview
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY=1x00000000000000000000AA
ARG NEXT_PUBLIC_TURNSTILE_TEST_MODE=true
ARG NEXT_PUBLIC_BOOKINGS_URL
ARG NEXT_PUBLIC_META_DATASET_ID
ARG NEXT_PUBLIC_GSC_VERIFICATION
ARG NEXT_PUBLIC_BING_VERIFICATION
ENV PROGRAMO_DEPLOYMENT_ENV=$PROGRAMO_DEPLOYMENT_ENV
ENV NEXT_PUBLIC_PROGRAMO_DEPLOYMENT_ENV=$PROGRAMO_DEPLOYMENT_ENV
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
ENV NEXT_PUBLIC_TURNSTILE_TEST_MODE=$NEXT_PUBLIC_TURNSTILE_TEST_MODE
ENV NEXT_PUBLIC_BOOKINGS_URL=$NEXT_PUBLIC_BOOKINGS_URL
ENV NEXT_PUBLIC_META_DATASET_ID=$NEXT_PUBLIC_META_DATASET_ID
ENV NEXT_PUBLIC_GSC_VERIFICATION=$NEXT_PUBLIC_GSC_VERIFICATION
ENV NEXT_PUBLIC_BING_VERIFICATION=$NEXT_PUBLIC_BING_VERIFICATION
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npx next build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=3000 HOSTNAME=0.0.0.0
RUN addgroup -S app && adduser -S app -G app
COPY --from=build --chown=app:app /app/public ./public
COPY --from=build --chown=app:app /app/.next/standalone ./
COPY --from=build --chown=app:app /app/.next/static ./.next/static
COPY --from=build --chown=app:app /app/src/content ./src/content
USER app
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \
  CMD wget -qO- http://127.0.0.1:3000/api/health || exit 1
CMD ["node", "server.js"]
